# Site settings
title: Newbe | Newbe便是新生，唯有不断蜕变才能焕然新生。
email: 472158246@qq.com
description: >
  Newbe | Newbe便是新生，唯有不断蜕变才能焕然新生。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.newbe.pro" # the base hostname & protocol for your site
author: Newbe

# Build settings
markdown: kramdown

contentsLabel: "目录"

exclude: [vendor,modules]
plugins:
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - jekyll-minifier
