# Site settings
title: Newbe
email: 472158246@qq.com
description: >
  Newbe | Newbe便是新生，唯有不断蜕变才能焕然新生。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.newbe.pro" # the base hostname & protocol for your site
author: Newbe

# Build settings
markdown: kramdown

highlighter: rouge

contentsLabel: "目录"

# seo tag
logo: /assets/i/logo.png
social:
  name: Newbe
  links:
    - https://github.com/newbe36524/
    - https://gitee.com/yks
    - https://user.qzone.qq.com/472158246
    - https://weibo.com/newbe36524
    - https://www.linkedin.com/in/%E5%9D%A4-%E4%BF%9E-09406a116/
lang: zh_cn

exclude: [vendor,modules]
plugins:
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  # - jekyll-minifier
